[workspace]
authors = ["sounkou-bioinfo <sounkoutoure@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "hellomojo"
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025111005,<0.26"

[target.osx-arm64.dependencies]
clang = ">=21.1.4,<22"

[target.linux-aarch64.dependencies]
gcc = ">=15.2.0,<15.3"
